"""Table productos added

Revision ID: 937b70a7f986
Revises: 2b85991c352f
Create Date: 2020-05-21 14:01:59.808249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b70a7f986'
down_revision = '2b85991c352f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('importe', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_folio'), 'cotizaciones', ['folio'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizaciones_folio'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
