"""empty message

Revision ID: eaa42aeeae00
Revises: 
Create Date: 2020-05-07 13:19:13.283973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa42aeeae00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('calle_numero', sa.String(length=100), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=100), nullable=True),
    sa.Column('nombre_corto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('calle_numero', sa.String(length=100), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_clientes_nombre_corto'), 'clientes', ['nombre_corto'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_nombre_corto'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
